#!/bin/sh -e

prefix="$1"
site="$prefix/usr/share/guile/site"

mkdir -p "$site"
mkdir -p "$prefix/usr/bin"
cp -t "$prefix/usr/bin" exe/rate exe/rate-modify
chmod 755 "$prefix/usr/bin/rate" "$prefix/usr/bin/rate-modify"
cp -rt "$site" modules/sph
chmod 755 "$site/sph/rate.scm"
